api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "showroom-delivery-function"
type = "function"
uid = "b0dc8893-eb7f-ef15-fc89-f5ffe1b6c366a5d387e9"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.delivery-options.transform.run"
  input_query = "src/cart_delivery_options_transform_run.graphql"
  export = "cart-delivery-options-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

[extensions.ui.paths]
create = "/app/delivery-customization/showroom-delivery-function/new"
details = "/app/delivery-customization/showroom-delivery-function/:id"
