# Learn more about configuring your checkout UI extension:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/configuration

api_version = "2026-07"

[[extensions]]
name = "showroom-pickup"
handle = "showroom-pickup"
type = "ui_extension"
uid = "5fb3a6f4-4124-ee56-4184-3f37b1e3d5f59ac3db49"

[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "purchase.checkout.pickup-location-list.render-before"

[extensions.capabilities]
api_access = true

[[extensions.metafields]]
namespace = "$app"
key = "showroom_availability"
